name: Deploy Production to Cloud Run
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run code checks
        run: npm run check

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/315620914732/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-action-965078087@rowan-fyi.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: europe-west1-docker.pkg.dev/rowan-fyi/rowan-fyi-repo/rowan-fyi:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "rowan-fyi"
          region: "europe-west1"
          image: "europe-west1-docker.pkg.dev/rowan-fyi/rowan-fyi-repo/rowan-fyi:latest"
          revision_traffic: "LATEST=100"
          flags: "--concurrency=250"
